// <auto-generated />
namespace Orders_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Actualization1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Actualization1));
        
        string IMigrationMetadata.Id
        {
            get { return "202203162139494_Actualization1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
